<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname(dirname($vendorDir))).'/default/files/composer';

return array(
    'BitcoinPHP\\BitcoinECDSA' => array($vendorDir . '/bitcoin-php/bitcoin-ecdsa/src'),
);
